# BaseGlobalPlanner:
#   use_grid_path: false
#   use_quadratic: true
#   use_dijkstra: false
#   old_navfn_behavior: true
#   allow_unknown: true
#   default_tolerance: 0.0
#   visualize_potential: false
#   lethal_cost: 255
#   neutral_cost: 50
#   cost_factor: 3
#   publish_potential: true
#   orientation_mode: 0
#   orientation_window_size: 1
#   outline_map: true

BaseGlobalPlanner:
  allow_unknown: true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  visualize_potential: true