global_frame: map
rolling_window: false
static_map: true

# Konfigurasi layer costmap
plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

static_layer:
    unknown_cost_value: -1
    lethal_cost_threshold: 255
    map_topic: map
    track_unknown_space: true

inflation_layer:
    inflation_radius: 0.1
    cost_scaling_factor: 0