global_frame: map
robot_base_frame: base_link
transform_tolerance: 0.5
robot_radius: 0.5
# footprint: [[-0.31, -0.69], [-0.31, 0.25], [0.31, 0,25], [0.31, -0.69]]
# footprint: [[-0.24, -0.24], [0.24, -0.24], [0.24, 0.24], [-0.24, 0.24]]
# footprint: [[-0.1, -0.1], [-0.1, 0.1], [0.1, 0.1], [-0.1, 0.1]]
# footprint: [[0, 0.15], [-0.15, -0.15], [0.15, -0.15]]
# footprint: [[-0.3,0.173], [0.3, 0.173], [0, -0.26]]
footprint: [[0.173, -0.3], [0.173, 0.3], [-0.26, 0]]

update_frequency: 0.5
publish_frequency: 2.0
rolling_window: false
track_unknown_space:  false

# width: 1
# height: 1
# resolution: 0.5
# origin_x: 0
# origin_y: 0

# plugins:
  # - {name: static, type: "costmap_2d::StaticLayer"}
  # - {name: inflation, type: "costmap_2d::InflationLayer"}
  # - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}

