TebLocalPlannerROS:
  dt_ref: 0.3
  dt_hysteresis: 0.1
  max_global_plan_lookahead_dist: 3.0
  global_plan_prune_distance: 1.0
  force_reinit_new_goal_dist: 1.0
  max_vel_x: 0.5
  max_vel_y: 0.5
  max_vel_theta: 1.0
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.2
  min_turning_radius: 0.0
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: False
  obstacle_avoidance_distance: 0.5
  costmap_obstacles_behind_robot_dist: 1.0
  weight_kinematics_forward_driveability: 1.0
  weight_kinematics_goal_angle: 1.0
  weight_optimaltime: 1.0
  weight_obstacle: 50.0
  weight_viapoint: 1.0
  weight_adapt_vel: 2.0